#!/usr/bin/env python3
"""Generate web/templates/copy.go from the EN object in web/static/js/i18n.js."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "web/static/js/i18n.js"
DST = ROOT / "web/templates/copy.go"


def main() -> None:
    src = SRC.read_text()
    m = re.search(r"var EN = \{([\s\S]*?)\n  \};", src)
    if not m:
        raise SystemExit("could not find EN object in web/static/js/i18n.js")
    body = m.group(1)
    pairs = re.findall(r'^\s+([a-z0-9_]+):\s*("(?:\\.|[^"\\])*"),?\s*$', body, re.M)
    raw_keys = re.findall(r"^\s+([a-z0-9_]+):", body, re.M)
    parsed = {k for k, _ in pairs}
    missing = [k for k in raw_keys if k not in parsed]
    if missing:
        raise SystemExit(f"unparsed EN keys: {missing}")

    lines = [
        "package templates",
        "",
        "// Code generated by scripts/gen_copy.py from web/static/js/i18n.js. DO NOT EDIT.",
        "",
        "// Copy is the English string for a template key. HTML renders this so labels never flash the key.",
        "func Copy(key string) string {",
        "\tswitch key {",
    ]
    for k, js in pairs:
        val = json.loads(js)
        go = json.dumps(val, ensure_ascii=False)
        lines.append(f'\tcase "{k}":')
        lines.append(f"\t\treturn {go}")
    lines += ["\tdefault:", "\t\treturn key", "\t}", "}"]
    DST.write_text("\n".join(lines) + "\n")
    print(f"wrote {DST.relative_to(ROOT)} ({len(pairs)} keys)")


if __name__ == "__main__":
    main()
