#!/usr/bin/env python3
"""Download HTMX, Alpine, Chart.js, and latin woff2 subsets of DM Sans + Fraunces."""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JS = ROOT / "web/static/js/vendor"
FONTS = ROOT / "web/static/fonts"
CSS = ROOT / "web/static/css/fonts.css"

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

SCRIPTS = {
    "htmx.min.js": "https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js",
    "alpine.min.js": "https://unpkg.com/alpinejs@3.14.8/dist/cdn.min.js",
    "chart.umd.min.js": "https://cdn.jsdelivr.net/npm/chart.js@4.4.6/dist/chart.umd.min.js",
}

FONT_CSS = (
    "https://fonts.googleapis.com/css2?"
    "family=DM+Sans:wght@400;500;600;700&"
    "family=Fraunces:wght@500;600;700&display=swap"
)


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as res:
        return res.read()


def is_latin(unicode_range: str) -> bool:
    return "U+0000-00FF" in unicode_range.replace(" ", "").upper()


def main() -> None:
    JS.mkdir(parents=True, exist_ok=True)
    FONTS.mkdir(parents=True, exist_ok=True)

    for name, url in SCRIPTS.items():
        dest = JS / name
        dest.write_bytes(fetch(url))
        print(f"wrote {dest.relative_to(ROOT)} ({dest.stat().st_size} bytes)")

    css = fetch(FONT_CSS).decode("utf-8")
    blocks = re.split(r"(?=@font-face)", css)
    seen_url: dict[str, str] = {}
    faces: dict[str, dict[str, str]] = {}
    for block in blocks:
        if "@font-face" not in block:
            continue
        urls = re.findall(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", block)
        ranges = re.findall(r"unicode-range:\s*([^;]+);", block)
        if not urls or not ranges or not is_latin(ranges[0]):
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block)
        weight = re.search(r"font-weight:\s*(\d+)", block)
        if not family or not weight:
            continue
        slug = family.group(1).lower().replace(" ", "-")
        src = urls[0]
        fname = seen_url.get(src)
        if fname is None:
            fname = f"{slug}.woff2"
            seen_url[src] = fname
            (FONTS / fname).write_bytes(fetch(src))
            print(f"wrote fonts/{fname}")
        info = faces.setdefault(slug, {"family": family.group(1), "fname": fname, "range": ranges[0].strip(), "weights": []})
        info["weights"].append(int(weight.group(1)))

    if not faces:
        raise SystemExit("no latin @font-face blocks found — Google CSS shape changed")

    for extra in FONTS.glob("*.woff2"):
        if extra.name not in {f["fname"] for f in faces.values()}:
            extra.unlink()

    out_faces = []
    for info in faces.values():
        lo, hi = min(info["weights"]), max(info["weights"])
        wght = str(lo) if lo == hi else f"{lo} {hi}"
        out_faces.append(
            "@font-face {\n"
            f"  font-family: '{info['family']}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {wght};\n"
            "  font-display: swap;\n"
            f"  src: url(\"/static/fonts/{info['fname']}\") format(\"woff2\");\n"
            f"  unicode-range: {info['range']};\n"
            "}"
        )
    CSS.write_text("/* latin variable subset; generated by scripts/vendor.py */\n\n" + "\n\n".join(out_faces) + "\n")
    print(f"wrote {CSS.relative_to(ROOT)} ({len(out_faces)} faces)")


if __name__ == "__main__":
    main()
